[project]
name = "oajf"
version = "0.1.0"
description = "OAJF - Open Access Journal Finder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-babel>=4.0.0",
    "gunicorn>=26.2.0",
    "ldap3>=2.9.1",
    "mariadb>=1.1.14",
    "openpyxl>=3.1.5",
    "requests>=2.34.2",
    "xlsxwriter>=3.2.9",
    "yacryptopan>=1.0.2",
]

[tool.uv]
